# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ClubRow' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ClubRow
  pod 'FSCalendar'
  pod 'SwiftEntryKit', '0.8.2'
  #  pod 'Presentr'
  pod 'SwiftyAvatar', '~> 1.1'
  pod 'XLSlidingContainer', '~> 2.0'
  pod 'IQKeyboardManagerSwift'

  # http
  pod 'Alamofire', '~> 4.7'

 # phoienx
  pod "SwiftPhoenixClient"
  pod 'SwiftyJSON', '~> 4.2'

 # progress 
  pod 'MKProgress', '~> 1.0.9'
  
 # pull to refress
  pod 'CRRefresh'
  
  # ViewPager & Tab
  pod 'BmoViewPager'

 # Alert
  pod 'Toast-Swift', '~> 4.0.0'
  
  # Live Video
  pod 'YouTubePlayer'
  
  # Chart & Graph
  pod 'ScrollableGraphView'
  
  # Analytics
  pod 'Firebase/Core'

end
